import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RootNav from "@/app/ui/root-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex h-screen flex-col overflow-hidden">
      <div className="w-full flex-none border-b-2 border-black">
        <RootNav />
      </div>
      <div className="flex-grow overflow-y-auto">
      {children}
      </div>
      </div>
      </body>
    </html>
  );
}
